[package]
name = "nyanko_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
glutin = "0.29"
gl = "0.14"
winit = "0.27"
raw-window-handle = "0.4"
cgmath = "0.18"
image = "0.24"
log = "0.4"
env_logger = "0.10"
shaderc = "0.8"

[build-dependencies]
shaderc = "0.8"

[features]
default = []

[[bin]]
name = "nyanko_engine"
path = "src/main.rs"

[[example]]
name = "basic_window"
path = "examples/basic/window.rs"

[[example]]
name = "basic_graphics"
path = "examples/basic/graphics.rs"

[[example]]
name = "basic_input"
path = "examples/basic/input.rs"
