[package]
name = "nyanko_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
cgmath = "0.18.0"
env_logger = "0.11.5"
gl = "0.14.0"
glfw = "0.58.0"
log = "0.4.17"
thiserror = "1.0.31"
nyanko_engine = { path = "../" }